version: "3"

services: 
    mongo:
        image: mongo:latest
        volumes: 
            - ./data/db/master:/data/db
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TZ=Asia/Shanghai
        container_name: qq-bot-ref_mongo
        networks:
            - qq-bot-ref
    mirai:
        build: bot
        environment: 
            - QQ_NUMBER=12345678
            - QQ_PASSWORD=pass
        networks: 
            - qq-bot-ref
        volumes:
            - ./bot/tmp:/tmp
        container_name: qq-bot-ref_mirai
    app:
        build: src
        volumes: 
            - ./env:/env
        environment: 
            - CONFIG_FILE=produce.json
        networks: 
            - qq-bot-ref
        depends_on: 
            - mongo
            - mirai
        container_name: qq-bot-ref_app
networks:
    qq-bot-ref:
